### ISSUE TITLE
Why IDENT is OFF ?

### ISSUE THREAD

**Issue by fahadmehar** [StormBit/stormbnc#2]
Why my BNC IDENT Is OFF ? I am getting ~  this on my IDENT and DALnet server is bit strick on Idents.

**Comment by rglx** [comment]
I've just enabled it, but in the future: **_DO NOT OPEN ISSUES ON GITHUB**_ for these kinds of technical matters. _Please use the IRC channel_, and _wait for awhile_, and make sure you clearly mention your BNC user-name so that we can contact you via email, should you disconnect ro become unreachable.

**Comment by fahadmehar** [comment]
I am really very sorry I have make a biggest mistake. Thank you so much... I will contact on that Idle channel next time.
